version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '/srv/data/jenkins_home:/var/jenkins_home'
volumes:
  jenkins_data:
    driver: local
